CREATE DATABASE IF NOT EXISTS sospedra;

USE sospedra;

-- Tipo de prendas
CREATE TABLE IF NOT EXISTS tipos_de_prendas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_es VARCHAR(50) NOT NULL,
    nombre_ca VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS prendas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_es VARCHAR(50) NOT NULL,
    nombre_ca VARCHAR(50) NOT NULL,
    imagen VARCHAR(255) NOT NULL,
    id_tipo_prenda INT NOT NULL,
    FOREIGN KEY (id_tipo_prenda) REFERENCES tipos_de_prendas(id)
);

CREATE TABLE IF NOT EXISTS prendas_imagenes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_prenda INT NOT NULL,
    ruta VARCHAR(255) NOT NULL,
    orden INT NOT NULL,
    FOREIGN KEY (id_prenda) REFERENCES prendas(id)
);

-- Tipos de prendas
INSERT INTO tipos_de_prendas (nombre_es, nombre_ca) VALUES 
('Camisa', 'Camisa'),
('Chaqueta de punto', 'Jaqueta de punt'),
('Jersei', 'Jersei'),
('Sobrecamisa', 'Sobrecamisa'),
('Parka', 'Parka'),
('Cinturones', 'Cinturons'),
('Trajes', 'Tratges'),
('Guantes', 'Guants'),
('Gorros', 'Gorros'),
('Abrigos', 'Abrigs'),
('Americanas', 'Americanes'),
('Pantalones', 'Pantalons'),
('Corbatas', 'Corbates'),
('Pañuelos y Bufandas', 'Mocadors i Bufandes'),
('Cuello alto', 'Coll alt');

-- Prendas
INSERT INTO prendas (nombre_es, nombre_ca, imagen, id_tipo_prenda) VALUES 
('Camisa', 'Camisa', '/img/camisas/camisa_azul.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_azul.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_circulos.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_flores.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_ovalo.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_rayas.jpeg', 1),
('Camisa', 'Camisa', '/img/camisas/camisa_estampado_rosa.jpeg', 1),
('Chaqueta', 'Chaqueta', '/img/chaquetas/de_punto/chaqueta_azul_pecho.jpeg', 2),
('Chaqueta', 'Chaqueta', '/img/chaquetas/de_punto/chaqueta_gris_pecho.jpeg', 2),
('Chaqueta', 'Chaqueta', '/img/chaquetas/de_punto/chaqueta_marron_pecho.jpeg', 2),
('Chaqueta', 'Chaqueta', '/img/chaquetas/de_punto/chaqueta_negra_pecho.jpeg', 2),
('Chaqueta', 'Chaqueta', '/img/chaquetas/de_punto/chaqueta_veix_pecho.jpeg', 2),
('Gorros', 'Gorros', '/img/gorros/gorros.jpeg', 9),
('Jersei', 'Jersei', '/img/jerseis/bandas/jersei_gris_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/bandas/jersei_veix_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cremallera/jersei_azul_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cremallera/jersei_azul_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cremallera/jersei_gris_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cremallera/jersei_veix_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello/jersei_azul_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello/jersei_rojo_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello/jersei_veix_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello/jersei_verde_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_abierto/jersei_azul_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_abierto/jersei_rojo_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_abierto/jersei_verde_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/cuello_alto/jersei_blanco_pecho.jpeg', 15),
('Jersei', 'Jersei', '/img/cuello_alto/jersei_gris_pecho.jpeg', 15),
('Jersei', 'Jersei', '/img/cuello_alto/jersei_negro_pecho.jpeg', 15),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_azul_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_azul_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_blanco_2_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_blanco_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_gris_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_gris_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_marron_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuello_cremallera/jersei_rojo_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuerdas/jersei_azul_pecho.jpeg', 3),
('Jersei', 'Jersei', '/img/jerseis/cuerdas/jersei_gris_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/cuerdas/jersei_gris_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/cuerdas/jersei_negro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_azul_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_blanco_negro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_blanco_negro_raya_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_gris_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_gris_negro_raya_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_gris_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_rojo_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/jersei_verde_oscuro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/rayas/jersei_negro_pecho.jpeg', 3),
('Jersei', 'Jersei', 'img/jerseis/rayas/jersei_veix_pecho.jpeg', 3),
('Parka', 'Parka', 'img/parkas/parka_azul_oscuro_pecho.webp', 5),
('Parka', 'Parka', 'img/parkas/parka_azul_pecho.webp', 5),
('Abrigos', 'Abrigs', 'img/abrigos/abrigo_azul_oscuro_pecho.webp', 10),
('Abrigos', 'Abrigs', 'img/abrigos/abrigo_marron_modelo_pecho.jpg', 10),
('Abrigos', 'Abrigs', 'img/abrigos/abrigo_negro_modelo_pecho.webp', 10),
('Abrigos', 'Abrigs', 'img/abrigos/abrigo_negro_pecho.webp', 10),
('Americanas', 'Americanes', 'img/americanas/americana_azul_gris_pecho.webp', 11),
('Trajes', 'Tratges', 'img/trajes/traje_azul_pecho.png', 7),
('Americanas', 'Americanes', 'img/americanas/americana_azul_interior_pecho.webp', 11),
('Trajes', 'Tratges', 'img/trajes/traje_gris_pecho.webp', 7),
('Americanas', 'Americanes', 'img/americanas/americana_marron_modelo_pecho.webp', 11),
('Trajes', 'Tratges', 'img/trajes/traje_negra_pecho.webp', 7),
('Sobrecamisa', 'Sobrecamisa', 'img/sobrecamisas/sobrecamisa_gris_pecho.webp', 4),
('Pantalones', 'Pantalons', 'img/pantalones/pantalon_negro.webp', 12),
('Pantalones', 'Pantalons', 'img/pantalones/pantalon_vaquero_claro.webp', 12),
('Pantalones', 'Pantalons', 'img/pantalones/pantalon_vaquero.png', 12);

-- Vincular imágenes adicionales para el carrusel
INSERT INTO prendas_imagenes (id_prenda, ruta, orden) VALUES 
(1, 'img/camisas/camisa_azul.jpeg', 0),
(2, 'img/camisas/camisa_estampado.jpeg', 0),
(3, 'img/camisas/camisa_estampado_azul.jpeg', 0),
(4, 'img/camisas/camisa_estampado_circulos.jpeg', 0),
(5, 'img/camisas/camisa_estampado_flores.jpeg', 0),
(6, 'img/camisas/camisa_estampado_ovalo.jpeg', 0),
(7, 'img/camisas/camisa_estampado_rayas.jpeg', 0),
(8, 'img/camisas/camisa_estampado_rosa.jpeg', 0),
(9, 'img/chaquetas/de_punto/chaqueta_azul_pecho.jpeg', 0),
(9, 'img/chaquetas/de_punto/chaqueta_azul_espalda.jpeg', 1),
(10, 'img/chaquetas/de_punto/chaqueta_gris_pecho.jpeg', 0),
(10, 'img/chaquetas/de_punto/chaqueta_gris_espalda.jpeg', 1),
(11, 'img/chaquetas/de_punto/chaqueta_marron_pecho.jpeg', 0),
(11, 'img/chaquetas/de_punto/chaqueta_marron_espalda.jpeg', 1),
(12, 'img/chaquetas/de_punto/chaqueta_negra_pecho.jpeg', 0),
(12, 'img/chaquetas/de_punto/chaqueta_negra_espalda.jpeg', 1),
(13, 'img/chaquetas/de_punto/chaqueta_veix_pecho.jpeg', 0),
(13, 'img/chaquetas/de_punto/chaqueta_veix_espalda.jpeg', 1),
(14, 'img/gorros/gorros.jpeg', 0),
(15, 'img/jerseis/bandas/jersei_gris_pecho.jpeg', 0),
(15, 'img/jerseis/bandas/jersei_gris_espalda.jpeg', 1),
(16, 'img/jerseis/bandas/jersei_veix_pecho.jpeg', 0),
(16, 'img/jerseis/bandas/jersei_veix_espalda.jpeg', 1),
(17, 'img/jerseis/cremallera/jersei_azul_pecho.jpeg', 0),
(17, 'img/jerseis/cremallera/jersei_azul_espalda.jpeg', 1),
(18, 'img/jerseis/cremallera/jersei_azul_oscuro_pecho.jpeg', 0),
(18, 'img/jerseis/cremallera/jersei_azul_oscuro_espalda.jpeg', 1),
(19, 'img/jerseis/cremallera/jersei_gris_pecho.jpeg', 0),
(19, 'img/jerseis/cremallera/jersei_gris_espalda.jpeg', 1),
(20, 'img/jerseis/cremallera/jersei_veix_pecho.jpeg', 0),
(20, 'img/jerseis/cremallera/jersei_veix_espalda.jpeg', 1),
(21, 'img/jerseis/cuello/jersei_azul_pecho.jpeg', 0),
(21, 'img/jerseis/cuello/jersei_azul_espalda.jpeg', 1),
(22, 'img/jerseis/cuello/jersei_rojo_pecho.jpeg', 0),
(22, 'img/jerseis/cuello/jersei_rojo_espalda.jpeg', 1),
(23, 'img/jerseis/cuello/jersei_veix_pecho.jpeg', 0),
(23, 'img/jerseis/cuello/jersei_veix_espalda.jpeg', 1),
(24, 'img/jerseis/cuello/jersei_verde_pecho.jpeg', 0),
(24, 'img/jerseis/cuello/jersei_verde_espalda.jpeg', 1),
(25, 'img/jerseis/cuello_abierto/jersei_azul_oscuro_pecho.jpeg', 0),
(25, 'img/jerseis/cuello_abierto/jersei_azul_oscuro_espalda.jpeg', 1),
(26, 'img/jerseis/cuello_abierto/jersei_rojo_pecho.jpeg', 0),
(26, 'img/jerseis/cuello_abierto/jersei_rojo_espalda.jpeg', 1),
(27, 'img/jerseis/cuello_abierto/jersei_verde_pecho.jpeg', 0),
(27, 'img/jerseis/cuello_abierto/jersei_verde_espalda.jpeg', 1),
(28, 'img/cuello_alto/jersei_blanco_pecho.jpeg', 0),
(28, 'img/cuello_alto/jersei_blanco_espalda.jpeg', 1),
(29, 'img/cuello_alto/jersei_gris_pecho.jpeg', 0),
(29, 'img/cuello_alto/jersei_gris_espalda.jpeg', 1),
(30, 'img/cuello_alto/jersei_negro_pecho.jpeg', 0),
(30, 'img/cuello_alto/jersei_negro_espalda.jpeg', 1),
(31, 'img/jerseis/cuello_cremallera/jersei_azul_pecho.jpeg', 0),
(31, 'img/jerseis/cuello_cremallera/jersei_azul_espalda.jpeg', 1),
(32, 'img/jerseis/cuello_cremallera/jersei_azul_oscuro_pecho.jpeg', 0),
(32, 'img/jerseis/cuello_cremallera/jersei_azul_oscuro_espalda.jpeg', 1),
(33, 'img/jerseis/cuello_cremallera/jersei_blanco_2_pecho.jpeg', 0),
(33, 'img/jerseis/cuello_cremallera/jersei_blanco_2_espalda.jpeg', 1),
(34, 'img/jerseis/cuello_cremallera/jersei_blanco_pecho.jpeg', 0),
(34, 'img/jerseis/cuello_cremallera/jersei_blanco_espalda.jpeg', 1),
(35, 'img/jerseis/cuello_cremallera/jersei_gris_pecho.jpeg', 0),
(35, 'img/jerseis/cuello_cremallera/jersei_gris_espalda.jpeg', 1),
(36, 'img/jerseis/cuello_cremallera/jersei_gris_oscuro_pecho.jpeg', 0),
(36, 'img/jerseis/cuello_cremallera/jersei_gris_oscuro_espalda.jpeg', 1),
(37, 'img/jerseis/cuello_cremallera/jersei_marron_pecho.jpeg', 0),
(37, 'img/jerseis/cuello_cremallera/jersei_marron_espalda.jpeg', 1),
(38, 'img/jerseis/cuello_cremallera/jersei_rojo_pecho.jpeg', 0),
(38, 'img/jerseis/cuello_cremallera/jersei_rojo_espalda.jpeg', 1),
(39, 'img/jerseis/cuerdas/jersei_azul_pecho.jpeg', 0),
(39, 'img/jerseis/cuerdas/jersei_azul_espalda.jpeg', 1),
(40, 'img/jerseis/cuerdas/jersei_gris_pecho.jpeg', 0),
(40, 'img/jerseis/cuerdas/jersei_gris_espalda.jpeg', 1),
(41, 'img/jerseis/cuerdas/jersei_gris_oscuro_pecho.jpeg', 0),
(41, 'img/jerseis/cuerdas/jersei_gris_oscuro_espalda.jpeg', 1),
(42, 'img/jerseis/cuerdas/jersei_negro_pecho.jpeg', 0),
(42, 'img/jerseis/cuerdas/jersei_negro_espalda.jpeg', 1),
(43, 'img/jerseis/jersei_azul_pecho.jpeg', 0),
(43, 'img/jerseis/jersei_azul_espalda.jpeg', 1),
(44, 'img/jerseis/jersei_blanco_negro_pecho.jpeg', 0),
(44, 'img/jerseis/jersei_blanco_negro_espalda.jpeg', 1),
(45, 'img/jerseis/jersei_blanco_negro_raya_pecho.jpeg', 0),
(45, 'img/jerseis/jersei_blanco_negro_raya_espalda.jpeg', 1),
(46, 'img/jerseis/jersei_gris_pecho.jpeg', 0),
(46, 'img/jerseis/jersei_gris_espalda.jpeg', 1),
(47, 'img/jerseis/jersei_gris_negro_raya_pecho.jpeg', 0),
(47, 'img/jerseis/jersei_gris_negro_raya_espalda.jpeg', 1),
(48, 'img/jerseis/jersei_gris_oscuro_pecho.jpeg', 0),
(48, 'img/jerseis/jersei_gris_oscuro_espalda.jpeg', 1),
(49, 'img/jerseis/jersei_rojo_pecho.jpeg', 0),
(49, 'img/jerseis/jersei_rojo_espalda.jpeg', 1),
(50, 'img/jerseis/jersei_verde_oscuro_pecho.jpeg', 0),
(50, 'img/jerseis/jersei_verde_oscuro_espalda.jpeg', 1),
(51, 'img/jerseis/rayas/jersei_negro_pecho.jpeg', 0),
(51, 'img/jerseis/rayas/jersei_negro_espalda.jpeg', 1),
(52, 'img/jerseis/rayas/jersei_veix_pecho.jpeg', 0),
(52, 'img/jerseis/rayas/jersei_veix_espalda.jpeg', 1),
(53, 'img/parkas/parka_azul_oscuro_pecho.webp', 0),
(54, 'img/parkas/parka_azul_pecho.webp', 0),
(55, 'img/abrigos/abrigo_azul_oscuro_pecho.webp', 0),
(56, 'img/abrigos/abrigo_marron_modelo_pecho.jpg', 0),
(57, 'img/abrigos/abrigo_negro_modelo_pecho.webp', 0),
(58, 'img/abrigos/abrigo_negro_pecho.webp', 0),
(59, 'img/americanas/americana_azul_gris_pecho.webp', 0),
(60, 'img/trajes/traje_azul_pecho.png', 0),
(61, 'img/americanas/americana_azul_interior_pecho.webp', 0),
(62, 'img/trajes/traje_gris_pecho.webp', 0),
(63, 'img/americanas/americana_marron_modelo_pecho.webp', 0),
(64, 'img/trajes/traje_negra_pecho.webp', 0),
(65, 'img/sobrecamisas/sobrecamisa_gris_pecho_webp', 0),
(66, 'img/pantalones/pantalon_negro.webp', 0),
(67, 'img/pantalones/pantalon_vaquero_claro.webp', 0),
(68, 'img/pantalones/pantalon_vaquero.png', 0);